apps/demo-react/LICENSE_React_Native.txt, apps/demo-react/package.json, apps/demo-react/src/RNTesterExamples/Button.tsx, apps/demo-react/src/RNTesterExamples/ExampleList.tsx, apps/demo-react/src/RNTesterExamples/Text.tsx, apps/demo-react/src/RNTesterExamples/View.tsx, apps/demo-react/src/components/AppContainer.tsx, apps/demo-react/src/components/View.tsx, package.json, packages/nativescript-yogalayout/react/Button.tsx, packages/nativescript-yogalayout/react/ReactNativeCompat.ts, packages/nativescript-yogalayout/react/Text.tsx, packages/nativescript-yogalayout/react/TextInput.tsx, packages/nativescript-yogalayout/react/View.tsx, packages/nativescript-yogalayout/react/index.ts, packages/nativescript-yogalayout/tsconfig.json
Based on an older version (circa June 2019) of this UI showcase: https://github.com/facebook/react-native/tree/dc80b2dcb52fadec6a573a9dd1824393f8c29fdc/packages/rn-tester/js/examples
This introduces provisional View, Text, TextInput, and Button components which have some API compatibility with the corresponding components in React Native. Just enough to pass most of the RNTester tests. Although I recommend people not to use these components in production, they serve to port a very handy set of RNTester test cases for us to check how well YogaLayout behaves.
This highlighted some issues:
I can only fit a screen's worth of test cases because the YogaLayout component doesn't seem to implement "auto" height. Thus it won't size to its contents and instead must take a fraction of the available …
=> feat(react): yoga tests, based on React Native's RNTester suite

packages/nativescript-image-zoom/index.android.ts
When using this view in my nativescript angular app I had problems with the view not showing the picture if it was under an `*ngIf` condition.
I figured it was because of the `initNativeView` function that didn't do all it was supposed to do in my case, because apparently the `[srcProperty]` wasn't already set.
This PR mainly fixes that, but the commit updates the whole file because of the pre-commit format script.
The real changes are:
- `initNativeView()` is simpler, always inits the manager and calls `resetImage` if the `src` is set.
- `[srcProperty.setNative](src)` always calls `resetImage()` and does not call `setBorderAndRadius()`
- `resetImage(reload)` always loads the image (with `manager.load(image)`) and always calls `setBorderAndRadius()`.
=> fix(image-zoom): fix android image-zoom component reset

packages/nativescript-stripe/index.android.ts
This change fixes the setter for expYear which was incorrectly setting this._expMonth instead of this._expYear.
=> Fix CardParams expMonth being set to expYear on Android

packages/nativescript-image-cache-it/common.ts
I noticed that the error events never fire when the image fails to load, which is caused by a mismatch in the event name. :)
=> bug(image-cache-it): fix event name for image load error

packages/nativescript-aws-sdk-s3/common.ts, packages/nativescript-aws-sdk-s3/index.ios.ts
Fix typeerror in iOS by making `defaultS3TransferUtility` and `defaultServiceManager` function calls.
Also fix typo for `AP_SOUTHEAST_2`.
=> fix: AWS S3 uploads for iOS

packages/nativescript-accordion/angular/index.ts, packages/nativescript-image-cache-it/angular/index.ts, packages/nativescript-stripe/angular/index.ts, packages/nativescript-stripe/angular/nativescript-stripe.directives.ts, packages/nativescript-yogalayout/angular/index.ts, packages/nativescript-youtubeplayer/angular/index.ts, packages/nativescript-youtubeplayer/angular/nativescript-youtubeplayer.directives.ts
require on angular packages breaks on angular 14+ (they're not processed by webpack)
=> fix: do not use require in angular packages

packages/nativescript-couchbase/platforms/android/include.gradle, packages/nativescript-couchbase/platforms/ios/Podfile, packages/nativescript-couchbase/typings/android-declarations.d.ts, packages/nativescript-couchbase/typings/android.d.ts, packages/nativescript-couchbase/typings/objc!CouchbaseLite.d.ts
This update is needed mainly for iOS as cocoapods since `3.0.0` include arm64 and can be run on simulator.
See: https://github.com/triniwiz/nativescript-plugins/issues/106
I also tested `3.0.0` on android and there were no breaking changes.
Fixes #106
=> chore: couchbase libs update to 3.0.0

packages/nativescript-stripe/index.ios.ts, packages/nativescript-stripe/standard/index.android.ts, packages/nativescript-stripe/standard/index.ios.ts
Hi @triniwiz,
I've fixed the issues #134 and #137 and partially the #135, this fixe reduce the number of call but not fixe it definitely
=> Fixe IOS issues

packages/nativescript-stripe/standard/index.ios.ts
If capturePayment does not return a StripePaymentIntent, this will allow payments to succeed. Discussed in #141
=> fix(stripe) Add null safe operator

packages/nativescript-stripe/standard/index.android.ts
Hi @triniwiz :)
This plugin doesn't handle the `Failed/Canceled` `3DS` authentication, plus there was an casual issue with the card for failed payment ending with `0341` that doesn't have the `component1` when capturing the payment causing app crash.
There is it :)
=> [Stripe][Android] Handle 3DS cancellation/Failed authentication

packages/nativescript-image-zoom/index.ios.ts
Fixes https://github.com/triniwiz/nativescript-plugins/issues/88 🥂
=> bug: fix missing parenthesis in NativeClass decorator

packages/nativescript-star-ratings/README.md, packages/nativescript-star-ratings/common.ts, packages/nativescript-star-ratings/index.ios.ts, packages/nativescript-stripe/index.ios.ts, packages/nativescript-stripe/standard/index.android.ts
Hi @triniwiz,
I add handling the Application delegate internally because I had a conflict between this plugin and `nativescript-community/universal-links` declaring a new delegate for Stripe return url causing the loose of the data for the univseral-link plugin, there was a work around to set the universal link from the new app delegate but I saw that will be useful as we don't need to handling the return url on the app side anymore and creating a delegation. Also this will be better approach to prevent conflict with other plugins.
PS: This solution is done by [nativescript-community](https://github.com/nativescript-community/universal-links/blob/master/src/universal-links/index.ios.ts)
=> [IOS] Handle Application delegate internally

packages/nativescript-stripe/standard/index.ios.ts
@triniwiz IOS return success when failed a 3DS payment.
I think this solution should be the same with android .. I have fixed this issue on android based on the paymentIntent status but I think it should be more complete such this way!
I am a little confused about those status, I think they will not be triggered on the payment process, for that I put them with the success
```ts
STPPaymentIntentStatusRequiresPaymentMethod
STPPaymentIntentStatusRequiresSource
STPPaymentIntentStatusRequiresSourceAction
```
What do you think ?
=> Fix [IOS] Payment Intent status

docs/src/api-reference/image-cache-it.md
Update docs to include the optional `headers` argument in the `getItem` method from changes in https://github.com/triniwiz/nativescript-plugins/commit/37145b05e303642211139da7ae59f0be4705cd3b
🥂
=> docs: update getItem args

packages/nativescript-couchbase/index.android.ts, packages/nativescript-couchbase/index.ios.ts
This ensures that method `deleteDocument` does not attempt to delete null instances and will return false in such a case.
This problem was more apparent on iOS as native call was not surrounded by try-catch.
=> fix(couchbase): Method deleteDocument tries to delete null documents

packages/nativescript-sse/common.ts, packages/nativescript-sse/index.android.ts, packages/nativescript-sse/index.ios.ts
Hello @triniwiz, we would like to use your @triniwiz/nativescript-sse plugin (that is not released yet) as an EventSource counterpart in our app. To achieve this we made these changes.
- `addEventListener`, and `removeEventListener` methods were empty in the "index.android.ts". they had some code in "index.ios.ts" but it was just to handle custom events and trigger `onMessage`. there is no need to do anything on android to get these custom events as they trigger onMessage automatically.
It was not possible to attach event handlers on both platforms; listener methods didn't contain a parameter to pass a handler.
`_eventListeners` object is added to store the added listeners' handlers by event name. `addEventListener`, and `removeEventListener` methods are updated to be used for managing …
=> feat(nativescript-sse): event listener support as in EventSource

packages/nativescript-image-cache-it/index.ios.ts
I was running into the following errors on iOS:
```
TypeError: Cannot set properties of null (setting ‘alpha’) 
TypeError: Cannot set properties of null (setting ‘image’)
```
I found that the errors happen when these properties are set after the view is destroyed.
This PR adds a check before setting these properties to prevent running into this error.
=> [ImageCacheIt][iOS] Add check before setting properties of nativeView

packages/nativescript-supabase-gotrue/AuthAdminApi.ts, packages/nativescript-supabase-gotrue/AuthClient.ts, packages/nativescript-supabase-gotrue/GoTrueAdminApi.ts, packages/nativescript-supabase-gotrue/GoTrueClient.ts, packages/nativescript-supabase-gotrue/index.ts, packages/nativescript-supabase-gotrue/lib/errors.ts, packages/nativescript-supabase-gotrue/lib/fetch.ts, packages/nativescript-supabase-gotrue/lib/helpers.ts, packages/nativescript-supabase-gotrue/lib/local-storage.ts, packages/nativescript-supabase-gotrue/lib/locks.ts, packages/nativescript-supabase-gotrue/lib/types.ts, packages/nativescript-supabase/SupabaseClient.ts
Updated to latest GoTrue client.
Added support for `allowExpiredSession` + adjusted session logic so if there's an existing session from storage, we keep it in case an authRetryableError happens (ie. the session expired, but we failed to refresh it). This allows the session to stay alive even when the user is offline, as a refresh will still happen once online.
=> feat(supabase): update gotrue, persist offline session

packages/nativescript-socketio/index.ios.ts
The problem:
Regular socket.io treats ```config.auth``` as a handshake payload. This feature is intentionally disabled in nativescript-socketio.
Solution:
Parse ```auth``` field as a ```auth_payload``` and pass it on connection.
=> Feature: Add handshake payload support for iOS

packages/nativescript-socketio/index.android.ts
About "extraHeaders":
emptyMap is immutable, so when ```headers.put(key, value)``` is called, Java throws ```java.lang.UnsupportedOperationException```.
Consider using HashMaps instead.
About "auth_payload":
This is a symmetric feature for my recent [iOS Handshake payload PR](https://github.com/triniwiz/nativescript-plugins/pull/194). It works similar, but utilises Socket options builder's ```setAuth``` instead.
=> [socket.io feature] Add auth payload for Android + fix extraHeaders

packages/nativescript-videorecorder/index.ios.ts
Cancelling the iOS camera does not resolve the recording promise. Fix this by calling the reject callback with the `{event: 'cancelled'}`
=> [nativescript-videorecorder] iOS Fix cancel event

packages/nativescript-ffmpeg/index.android.ts, packages/nativescript-videorecorder/index.ios.ts
Fixes missing export of `LogLevel` for Android
```
export 'LogLevel' (imported as 'LogLevel') was not found in '@triniwiz/nativescript-ffmpeg' (possible exports: FFmpeg, TNSLog, TNSMediaInformation, TNSMediaStream, TNSReturnCode, TNSSession, TNSStatistics)
```
=> [Android] Fix export 'LogLevel' (imported as 'LogLevel') was not found in '@triniwiz/nativescript-ffmpeg'

packages/nativescript-stripe/paymentSheet/index.android.ts, packages/nativescript-stripe/paymentSheet/index.ios.ts
So, this simple change brings:
- for ios, the ability to now have propert "cancelled" message returned in the thrown error - previously it was throwing "unknown" from default case, which was no good.
- for android: alignment with ios, to return "cancelled" rather than "canceled". 
Appreciate the bottom one (android) would possibly be a breaking change, however: if anyone did implement this ever, then they must already be catching both the case of "cancelled" and "canceled" - as that seems to be what it USED to be in ios as well (assuming that the code in the package already worked sometime back).
=> (nativescript-stripe) Fix paymentSheet returning "unknown" in iOS & misspelled word in Android
